name: Combined Test
on:
  push:
jobs:
  workflow-analysis:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Create dir
        run: |
          mkdir mydata
          ls
         
      - name: Download Coffea-Base image
        run: docker pull coffeateam/coffea-base
        
      - name: Run Coffea-Base container
        run: docker run --rm -v $PWD:/code coffeateam/coffea-base bash -c 'cd code/analysis/coffea/ && python coffea_plot.py && ls && mv *.png ../../mydata/ && ls'

      - name: Download ROOT-Base image
        run: docker pull rootproject/root

      - name: Run ROOT-Base container
        run: docker run --rm -v $PWD:/code rootproject/root bash -c 'cd ../code/analysis/coffea/ && python coffea_plot.py && ls && mv *.png ../../mydata/ && ls'

      - name: Upload results
        uses: actions/upload-artifact@v3
        with:
          name: Analysis Results
          path: mydata/
