name: TEST

on:
  push:
  
jobs:
  workflow-analysis:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Create dir
        run: |
          mkdir mydata
          ls
          
      - name: Download Coffea-Base image
        run: docker pull coffeateam/coffea-base
        
      - name: Run Coffea-Base container
        run: docker run --rm -v $PWD:/workdir coffeateam/coffea-base bash -c 'cd workdir && python analysis/coffea/coffea_plot.py'

      - name: Save results
        run: |
          echo "save results"

      - name: Upload results
        uses: actions/upload-artifact@v3
        with:
          name: Analysis Results
          path: results/
